# styles.py
# 本文件定义了所有可用的渲染主题。
# 每个主题都是一个字典，键是HTML标签名，值是对应的内联CSS样式字符串。

# 蓝色主题 - 专业、商务风格
BLUE = {
    'body': 'font-family: -apple-system-font,BlinkMacSystemFont, Helvetica Neue, PingFang SC, Hiragino Sans GB , Microsoft YaHei UI , Microsoft YaHei ,Arial,sans-serif; font-size: 15px; line-height: 1.75; text-align: left;',
    'wrapper': 'width: 100%; max-width: 750px; margin: 0 auto;',
    'section': 'text-align: left; line-height: 1.75; font-family: -apple-system-font,BlinkMacSystemFont, Helvetica Neue, PingFang SC, Hiragino Sans GB , Microsoft YaHei UI , Microsoft YaHei ,Arial,sans-serif; font-size: 15px',
    'p': 'margin: 1.5em 8px; letter-spacing: 0.1em; color: hsl(var(--foreground));',
    'h1': 'text-align: center; line-height: 1.75; font-size: 23.8px; display: table; padding: 0.5em 1em; border-bottom: 2px solid #0F4C81; margin: 2em auto 1em; color: hsl(var(--foreground)); font-weight: bold; text-shadow: 2px 2px 4px rgba(0,0,0,0.1);',
    'h2': 'text-align: center; line-height: 1.75; font-size: 22.1px; display: table; padding: 0.3em 1em; margin: 4em auto 2em; color: #fff; background: #0F4C81; font-weight: bold; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);',
    'h3': 'line-height: 1.2; font-size: 20.4px; padding-left: 12px; border-left: 4px solid #0F4C81; margin: 2em 8px 0.75em 0; color: hsl(var(--foreground)); font-weight: bold; border-bottom: 1px dashed #0F4C81;',
    'h4': 'font-size: 18.7px; margin: 2em 8px 0.5em; color: #0F4C81; font-weight: bold;',
    'h5': 'font-size: 17px; margin: 1.5em 8px 0.5em; color: #0F4C81; font-weight: bold;',
    'ul': 'list-style-type: none; padding-left: 1em; margin: 1em 0;',
    'ol': 'list-style-type: none; padding-left: 1em; margin: 1em 0;',
    'li': 'margin-bottom: 0.5em;',
    'a': 'color: #576b95; text-decoration: none;',
    'blockquote': 'font-style: italic; padding: 1em 1em 1em 2em; border-left: 4px solid #0F4C81; border-radius: 6px; color: rgba(0,0,0,0.6); background: var(--blockquote-background); margin-bottom: 1em; box-shadow: 0 4px 6px rgba(0,0,0,0.05);',
    'hr': 'border-style: solid; border-width: 2px 0 0; border-color: rgba(0,0,0,0.1); transform-origin: 0 0; transform: scale(1, 0.5); height: 1px; margin: 2em 0; border: none; background: linear-gradient(to right, rgba(0,0,0,0), rgba(0,0,0,0.1), rgba(0,0,0,0));',
    'table': 'border-collapse: collapse; margin: 1em 8px; width: calc(100% - 16px); box-shadow: 0 4px 8px rgba(0,0,0,0.1); border-radius: 8px; overflow: hidden;',
    'thead': 'background: rgba(0, 0, 0, 0.05); font-weight: bold; color: #3f3f3f;',
    'td': 'border: 1px solid #dfdfdf; padding: 0.5em 1em; color: #3f3f3f; word-break: keep-all;',
    'th': 'border: 1px solid #dfdfdf; padding: 0.5em 1em; color: #3f3f3f; word-break: keep-all;',
    'code_inline': 'background: rgba(27, 31, 35, 0.05); color: rgb(221, 17, 68); padding: 3px 5px; border-radius: 4px; font-size: 15.3px;',
    'pre': 'background: #1E1E1E; border: 1px solid #30363d; border-radius: 8px; margin: 1em 8px; box-shadow: rgba(0, 0, 0, 0.05) 0px 0px 10px 0px inset; overflow: auto; padding: 1em;',
    'code_block': 'display: -webkit-box; overflow-x: auto; text-indent: 0; font-family: "Fira Code", Menlo, "Operator Mono", Consolas, Monaco, monospace;',
    'img': 'display: block; max-width: 100%; height: auto; margin: 0 auto; border-radius: 8px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);',
    'figcaption': 'text-align: center; font-size: 0.8em; color: #888;',
    'strong': 'color: #0F4C81; font-weight: bold;',
}

# 优雅主题 - 简洁、现代，带有阴影效果
NICE = {
    'section': 'padding: 0 30px; font-family: ptima-Regular; word-break: break-all;',
    'body': 'font-size: 14px; letter-spacing: 0.05em; color:#595959;',
    'p': 'margin-top: 5px; margin-bottom: 0.8em; line-height: 26px; word-spacing: 3px; letter-spacing: 3px; text-align: left; color: #3e3e3e; font-size: 15px; text-indent: 2em;',
    'h1': 'margin: 1.2em 0 1em; padding: 0; font-weight: bold; color:#35b378;',
    'h1 .content': '',
    'h1:after': '',
    'h2': 'min-height: 32px; line-height: 32px; border-bottom: solid 1px #000000; color: #35b378; display: inline-block; border-bottom-width: 0px; border-bottom-style: solid; border-color: #35b378; padding-top: 5px; padding-right: 0.5em; padding-left: 0.5em; font-size: 23px; margin: 1em 0 0rem 0; padding: 0.5em 0; text-align: left; font-weight: bold;',
    'h2 .content': '',
    'h2:after': '',
    'h3': 'margin: 1.2em 0 1em; padding: 0; font-weight: bold; color: #35b378;',
    'h3 .content': '',
    'h3:after': '',
    'ul': 'list-style-type: none; padding-left: 1em; margin: 1em 0;',
    'ol': 'list-style-type: none; padding-left: 1em; margin: 1em 0;',
    'li': 'margin-bottom: 0.5em;',
    'li section': 'margin: 0;',
    'blockquote': 'margin: 10px 5px; border-left: 3px solid #35b378; border-right: 0px solid #35b378; color: #616161; quotes: none; background: #FBF9FD;',
    'blockquote p': '',
    'a': 'color: #35b378; border-bottom: 1px solid #35b378;',
    'table': 'border-collapse: collapse; width: 100%; margin: 1em 0;',
    'th': 'border: 1px solid #ccc; padding: 0.5em 1em; text-align: left; background-color: #f0f0f0; font-weight: bold;',
    'td': 'border: 1px solid #ccc; padding: 0.5em 1em; text-align: left;',
    'strong': 'font-weight: bold;',
    'img': 'display: block; max-width: 100%; height: auto; margin: 0 auto; border-radius: 8px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);', # 新增图片样式
    'pre': 'background: #1E1E1E; border: 1px solid #30363d; border-radius: 6px; padding: 1em; margin: 1em 0; overflow: auto;',
    'code_block': 'font-family: "Fira Code", Menlo, "Operator Mono", Consolas, Monaco, monospace; font-size: 0.9em;',
}

# 绿色主题 - 清新、自然风格
GREEN = {
    'section': 'font-size: 15px; padding: 0 30px; word-spacing: 0px; word-break: break-word; word-wrap: break-word; text-align: justify; line-height: 1.25; color: #2b2b2b; font-family: Optima-Regular, Optima, PingFangTC-Light, PingFangSC-light, PingFangTC-light; letter-spacing: 2px; background-image: linear-gradient(90deg, rgba(50, 0, 0, 0.04) 3%, rgba(0, 0, 0, 0) 3%), linear-gradient(360deg, rgba(50, 0, 0, 0.04) 3%, rgba(0, 0, 0, 0) 3%); background-size: 20px 20px; background-position: center center;',
    'h1': "margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 25px;",
    'h1.prefix': "font-weight: bold; color: #40B8FA; display: none;",
    'h1.content': "display: inline-block; font-weight: bold; color: #40B8FA;",
    'h1.suffix': "display: inline-block; font-weight: bold; color: #40B8FA;",
    'h2': "margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 22px; display: block; border-bottom: 4px solid #40B8FA;",
    'h2.prefix': "display: flex; width: 20px; height: 20px; background-size: 20px 20px; margin-bottom: -22px;",
    'h2.content': "display: flex; color: #40B8FA; font-size: 20px; margin-left: 25px;",
    'h2.suffix': "display: flex; box-sizing: border-box; width: 200px; height: 10px; border-top-left-radius: 20px; background: RGBA(64, 184, 250, .5); color: rgb(255, 255, 255); font-size: 16px; letter-spacing: 0.544px; justify-content: flex-end; float: right; margin-top: -10px; box-sizing: border-box !important; overflow-wrap: break-word !important;",
    'h3': "font-size: 17px; font-weight: bold; text-align: center; margin-top: 20px; margin-bottom: 20px;",
    'h3.prefix': "display: none;",
    'h3.content': "display: inline-block; color: #2b2b2b; border-bottom: 2px solid RGBA(79, 177, 249, .65); padding-bottom: 2px;",
    'h3.suffix': "display: none;",
    'p': "padding-top: 8px; padding-bottom: 0.8em; line-height: 26px; color: #2b2b2b; margin: 0 0 1em 0; letter-spacing: 2px; font-size: 14px; word-spacing: 2px; text-indent: 2em;",
    'hr': "margin: 0; margin-top: 10px; margin-bottom: 10px; height: 1px; padding: 0; border: none; border-top: 2px solid #3BAAFA;",
    'ul': 'list-style-type: none; padding-left: 1em; margin: 1em 0;',
    'ol': 'list-style-type: none; padding-left: 1em; margin: 1em 0;',
    'li': 'margin-bottom: 0.5em;',
    'strong': "color: #3594F7; font-weight: bold;",
    'table': "width: 100%; border-collapse: collapse; margin: 10px 0;",
    'th': "font-size: 15px; font-weight: bold; background-color: #f0f0f0; color: #595959; border: 1px solid #ccc; padding: 5px 10px;",
    'td': "font-size: 15px; color: #595959; border: 1px solid #ccc; padding: 5px 10px;",
    'code_inline': "color: #3594F7; background: RGBA(59, 170, 250, .1); display: inline-block; padding: 0 2px; border-radius: 2px; height: 21px; line-height: 22px;",
    'pre': 'background: #1E1E1E; border: 1px solid #30363d; border-radius: 6px; padding: 1em; margin: 1em 0; overflow: auto;',
    'code_block': 'font-family: "Fira Code", Menlo, "Operator Mono", Consolas, Monaco, monospace; font-size: 0.9em;',
    'a': "color: #40B8FA; font-weight: normal; border-bottom: 1px solid #3BAAFA;",
    'img': 'display: block; max-width: 100%; height: auto; margin: 0 auto; border-radius: 8px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);',
    'figcaption': "display: block; font-size: 14px; color: #2b2b2b;",
}

# 极客黑主题 - 模仿技术博客风格
GEEK_BLACK = {
    'section': 'font-size: 15px; color: black; padding: 0 30px; line-height: 1.6; word-spacing: 0px; letter-spacing: 0px; word-break: break-word; word-wrap: break-word; text-align: justify; font-family: Optima-Regular, Optima, PingFangSC-light, PingFangTC-light, \'PingFang SC\', Cambria, Cochin, Georgia, Times, \'Times New Roman\', serif;',
    'blockquote': 'display: block; font-size: 0.9em; overflow: auto; overflow-scrolling: touch; border-left: 4px solid rgb(221, 221, 221); background: rgba(0, 0, 0, 0.05); padding-top: 10px; padding-bottom: 10px; padding-right: 1em; padding-left: 1em; color: rgb(119, 119, 119); quotes: none; margin-top: 1.2em; margin-bottom: 1.2em;',
    'blockquote p': 'padding-top: 8px; padding-bottom: 8px; box-sizing: border-box; text-align: start; white-space: normal; text-size-adjust: auto; margin: 0px; font-size: 15px; font-family: -apple-system-font, BlinkMacSystemFont, \'Helvetica Neue\', \'PingFang SC\', \'Hiragino Sans GB\', \'Microsoft YaHei UI\', \'Microsoft YaHei\', Arial, sans-serif; color: rgb(119, 119, 119); line-height: 1.75em;',
    'p': 'padding: 0; margin: 0 0 0.8em 0; color: black; box-sizing: border-box; font-family: \'Helvetica Neue\', Helvetica, \'Segoe UI\', Arial, freesans, sans-serif; font-size: 14px; text-align: start; white-space: normal; text-size-adjust: auto; line-height: 1.75em;',
    'strong': 'font-weight: bold; color: black;',
    'a': 'text-decoration: none; word-wrap: break-word; font-weight: bold; color: rgb(239, 112, 96); border-bottom: 1px solid rgb(239, 112, 96);',
    'h1': 'font-weight: bold; color: black; font-size: 24px; margin-top: -0.46em; margin-bottom: 0.1em; border-bottom: 2px solid rgb(198, 196, 196); box-sizing: border-box;',
    'h1 .content': 'padding-top: 5px; padding-bottom: 5px; color: rgb(160, 160, 160); font-size: 13px; line-height: 2; box-sizing: border-box;',
    'h2': 'margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 22px; margin: 10px auto; height: 40px; background-color: rgb(251, 251, 251); border-bottom: 1px solid rgb(246, 246, 246); overflow: hidden; box-sizing: border-box;',
    'h2 .content': 'margin-left: -10px; display: inline-block; width: auto; height: 40px; background-color: rgb(33, 33, 34); border-bottom-right-radius: 100px; color: rgb(255, 255, 255); padding-right: 30px; padding-left: 30px; line-height: 40px; font-size: 16px;',
    'h3': 'margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 20px; margin: 20px auto 5px; border-top: 1px solid rgb(221, 221, 221); box-sizing: border-box;',
    'h3 .content': 'margin-top: -1px; padding-top: 6px; padding-right: 5px; padding-left: 5px; font-size: 17px; border-top: 2px solid rgb(33, 33, 34); display: inline-block; line-height: 1.1;',
    'ul': 'list-style-type: none; padding-left: 1em; margin: 1em 0;',
    'ol': 'list-style-type: none; padding-left: 1em; margin: 1em 0;',
    'li': 'margin-bottom: 0.5em;',
    'li section': 'margin: 0;',
    'code_inline': 'font-size: 14px; word-wrap: break-word; padding: 2px 4px; border-radius: 4px; margin: 0 2px; background-color: rgba(27,31,35,.05); font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; word-break: break-all; color: rgb(239, 112, 96);',
    'em': 'font-style: italic; color: black;',
    'hr': 'height: 1px; margin: 0; margin-top: 10px; margin-bottom: 10px; border: none; border-top: 1px solid black;',
    'table': 'display: table; text-align: left;',
    'thead': 'border: 0; border-top: 1px solid #ccc; background-color: white;',
    'th': 'font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; font-weight: bold; background-color: #f0f0f0;',
    'td': 'font-size: 16px; border: 1px solid #ccc; padding: 5px 10px;',
    'pre': 'background: #1E1E1E; border: 1px solid #30363d; border-radius: 6px; padding: 1em; margin: 1em 0; overflow: auto;',
    'code_block': 'font-family: "Fira Code", Menlo, "Operator Mono", Consolas, Monaco, monospace; font-size: 0.9em;',
    'img': 'display: block; max-width: 100%; height: auto; margin: 0 auto; border-radius: 8px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);',
    'figcaption': 'margin-top: 5px; text-align: center; color: #888; font-size: 14px;',
    'footnote-word': 'font-weight: bold; color: #ff3502;',
    'footnote-ref': 'line-height: 0; font-weight: bold; color: rgb(239, 112, 96);',
    'imageflow-layer1': 'margin: 1em auto; white-space: normal; border: 0px none; padding: 0px; overflow: hidden;',
    'imageflow-layer2': 'white-space: nowrap; width: 100%; overflow-x: scroll;',
    'imageflow-layer3': 'display: inline-block; word-wrap: break-word; white-space: normal; vertical-align: middle; width: 100%;',
    'imageflow-img': 'display: inline-block; max-width: 100%; height: auto; margin: auto;',
    'footnotes-sep': 'margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 20px; margin: 20px auto 5px; border-top: 1px solid rgb(221, 221, 221); box-sizing: border-box;',
    'footnotes-sep span': 'display: block;',
    'footnote-item': 'display: flex;',
    'footnote-num': 'display: inline; width: 10%; background: none; font-size: 80%; opacity: 0.6; line-height: 26px; font-family: ptima-Regular, Optima, PingFangSC-light, PingFangTC-light, \'PingFang SC\', Cambria, Cochin, Georgia, Times, \'Times New Roman\', serif;',
    'footnote-item p': 'padding-top: 8px; padding-bottom: 8px; box-sizing: border-box; margin-bottom: 16px; font-family: \'Helvetica Neue\', Helvetica, \'Segoe UI\', Arial, freesans, sans-serif; text-align: start; white-space: normal; text-size-adjust: auto; display: inline; font-size: 14px; width: 90%; padding: 0px; margin: 0; line-height: 26px; color: black; word-break: break-all; width: calc(100%-50);',
    'footnote-item p em': 'font-style: italic; color: black;',
}

# 橙红色主题 - 温暖、活泼风格
ORANGE_RED = {
    'section': 'font-size: 15px; color: black; padding: 0 30px; line-height: 1.6; word-spacing: 0px; letter-spacing: 0px; word-break: break-word; word-wrap: break-word; text-align: justify; font-family: Optima-Regular, Optima, PingFangSC-light, PingFangTC-light, \'PingFang SC\', Cambria, Cochin, Georgia, Times, \'Times New Roman\', serif;',
    'blockquote': 'display: block; font-size: 0.9em; overflow: auto; overflow-scrolling: touch; border-left: 3px solid rgba(0, 0, 0, 0.4); color: #6a737d; padding-top: 10px; padding-bottom: 10px; padding-left: 20px; padding-right: 10px; margin-bottom: 20px; margin-top: 20px; border-left-color: rgb(239, 112, 96); background: #fff9f9;',
    'blockquote p': 'font-size: 16px; padding-top: 8px; padding-bottom: 8px; margin: 0px; color: black; line-height: 26px;',
    'p': 'font-size: 15px; padding: 0; margin: 0 0 0.8em 0; line-height: 26px; color: black;',
    'strong': 'font-weight: bold; color: black;',
    'a': 'text-decoration: none; word-wrap: break-word; font-weight: bold; color: rgb(239, 112, 96); border-bottom: 1px solid rgb(239, 112, 96);',
    'h2': 'margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; border-bottom: 2px solid rgb(239, 112, 96); font-size: 1.3em;',
    'h2 .content': 'display: inline-block; font-weight: bold; background: rgb(239, 112, 96); color: #ffffff; padding: 3px 10px 1px; border-top-right-radius: 3px; border-top-left-radius: 3px; margin-right: 3px;',
    'h2 span': 'display: inline-block; vertical-align: bottom; border-bottom: 36px solid #efebe9; border-right: 20px solid transparent;',
    'ul': 'list-style-type: none; padding-left: 1em; margin: 1em 0;',
    'ol': 'list-style-type: none; padding-left: 1em; margin: 1em 0;',
    'li': 'margin-bottom: 0.5em;',
    'li section': 'margin: 0;',
    'h3': 'margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 20px;',
    'h1': 'margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 24px;',
    'code_inline': 'font-size: 14px; word-wrap: break-word; padding: 2px 4px; border-radius: 4px; margin: 0 2px; background-color: rgba(27,31,35,.05); font-family: Operator Mono, Consolas, Monaco, Menlo, monospace; word-break: break-all; color: rgb(239, 112, 96);',
    'em': 'font-style: italic; color: black;',
    'hr': 'height: 1px; margin: 0; margin-top: 10px; margin-bottom: 10px; border: none; border-top: 1px solid black;',
    'table': 'display: table; text-align: left;',
    'thead': 'border: 0; border-top: 1px solid #ccc; background-color: white;',
    'th': 'font-size: 16px; border: 1px solid #ccc; padding: 5px 10px; font-weight: bold; background-color: #f0f0f0;',
    'td': 'font-size: 16px; border: 1px solid #ccc; padding: 5px 10px;',
    'pre': 'background: #1E1E1E; border: 1px solid #30363d; border-radius: 6px; padding: 1em; margin: 1em 0; overflow: auto;',
    'code_block': 'font-family: "Fira Code", Menlo, "Operator Mono", Consolas, Monaco, monospace; font-size: 0.9em;',
    'img': 'display: block; max-width: 100%; height: auto; margin: 0 auto; border-radius: 8px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);',
    'figcaption': 'margin-top: 5px; text-align: center; color: #888; font-size: 14px;',
    'footnote-word': 'font-weight: bold; color: #ff3502;',
    'footnote-ref': 'line-height: 0; font-weight: bold; color: rgb(239, 112, 96);',
    'imageflow-layer1': 'margin: 1em auto; white-space: normal; border: 0px none; padding: 0px; overflow: hidden;',
    'imageflow-layer2': 'white-space: nowrap; width: 100%; overflow-x: scroll;',
    'imageflow-layer3': 'display: inline-block; word-wrap: break-word; white-space: normal; vertical-align: middle; width: 100%;',
    'imageflow-img': 'display: inline-block; max-width: 100%; height: auto; margin: auto;',
    'footnotes-sep': 'margin-top: 30px; margin-bottom: 15px; font-weight: bold; color: black; font-size: 20px;',
    'footnotes-sep span': 'display: block;',
    'footnote-item': 'display: flex;',
    'footnote-num': 'display: inline; width: 10%; background: none; font-size: 80%; opacity: 0.6; line-height: 26px; font-family: ptima-Regular, Optima, PingFangSC-light, PingFangTC-light, \'PingFang SC\', Cambria, Cochin, Georgia, Times, \'Times New Roman\', serif;',
    'footnote-item p': 'padding-top: 8px; padding-bottom: 8px; display: inline; font-size: 14px; width: 90%; padding: 0px; margin: 0; line-height: 26px; color: black; word-break: break-all; width: calc(100%-50);',
    'footnote-item p em': 'font-style: italic; color: black;',
}

# 蓝色辉光主题 - 赛博朋克、科技感风格
BLUE_GLOW = {
    'section': 'font-size: 15px; color: black; padding: 0 30px; line-height: 1.6; word-spacing: 0px; letter-spacing: 0px; word-wrap: break-word; text-align: justify; font-family: \'PingFang SC\', \'Microsoft YaHei\', sans-serif; word-break: break-all;',
    'blockquote': 'display: block; font-size: 0.9em; overflow: auto; overflow-scrolling: touch; border-left: 4px solid #0077ff; color: #6a737d; padding: 1em; margin: 1.5em 0; background: #f0f8ff; border-radius: 8px; box-shadow: 0 2px 10px rgba(0, 119, 255, 0.1);',
    'blockquote p': 'font-size: 16px; margin: 0; line-height: 1.7; color: #555;',
    'p': 'font-size: 15px; padding: 0; margin: 0 0 1em 0; line-height: 1.8; color: #444;',
    'strong': 'font-weight: bold; color: #0056b3; text-shadow: 0 0 3px rgba(0, 86, 179, 0.3);',
    'a': 'text-decoration: none; word-wrap: break-word; border-bottom: 1px solid #00aaff; color: #0077ff; font-weight: bold; text-shadow: 0 0 5px rgba(0, 119, 255, 0.5);',
    'h1': 'margin: 1.5em 0 1em; color: #0056b3; font-size: 1.8em; font-weight: bold; border-bottom: 2px solid #0077ff; text-align: center; text-shadow: 0 0 10px rgba(0, 119, 255, 0.3), 0 0 20px rgba(0, 119, 255, 0.2);',
    'h2': 'margin: 2em 0 1em; font-weight: bold; color: #0066cc; font-size: 1.5em; border-bottom: 1px solid #0077ff; padding-bottom: 0.3em; text-shadow: 0 0 8px rgba(0, 119, 255, 0.3);',
    'h3': 'margin: 1.5em 0 0.8em; font-weight: bold; color: #0077ff; font-size: 1.3em; text-shadow: 0 0 6px rgba(0, 119, 255, 0.2);',
    'ul': 'list-style-type: none; padding-left: 1em; margin: 1em 0;',
    'ol': 'list-style-type: none; padding-left: 1em; margin: 1em 0;',
    'li': 'margin-bottom: 0.5em;',
    'li section': 'margin: 0;',
    'code_inline': 'font-size: 14px; word-wrap: break-word; padding: 3px 5px; border-radius: 4px; margin: 0 2px; background-color: rgba(0, 119, 255, 0.1); box-shadow: 0 0 8px rgba(0, 119, 255, 0.2); font-family: "Fira Code", Consolas, Monaco, monospace; word-break: break-all; color: #0056b3;',
    'h4': 'margin: 1.5em 0 0.8em; font-weight: bold; color: #0077ff; font-size: 1.1em;',
    'h5': 'margin: 1.5em 0 0.8em; font-weight: bold; color: #0077ff; font-size: 1em;',
    'h6': 'margin: 1.5em 0 0.8em; font-weight: bold; color: #0077ff; font-size: 0.9em;',
    'em': 'font-style: italic; color: #0066cc;',
    'img': 'display: block; max-width: 100%; height: auto; margin: 1.5em auto; border-radius: 8px; box-shadow: 0 8px 25px rgba(0, 119, 255, 0.2);',
    'figcaption': 'margin-top: 0.5em; text-align: center; color: #888; font-size: 14px;',
    'hr': 'height: 1px; border: none; width: 80%; margin: 2em auto; background-image: linear-gradient(to right, transparent, #0077ff, transparent);',
    'table': 'display: table; text-align: left; margin: 1.5em auto; width: auto; border-collapse: collapse; box-shadow: 0 4px 15px rgba(0, 119, 255, 0.15);',
    'th': 'font-size: 16px; border: 1px solid #add8e6; padding: 10px 15px; background-color: #f0f8ff; color: #0056b3; font-weight: bold;',
    'td': 'font-size: 16px; border: 1px solid #add8e6; padding: 10px 15px; color: #333;',
    'pre': 'background: #0d1117; border: 1px solid #30363d; border-radius: 8px; margin: 1.5em 0; box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3); overflow: auto; padding: 1em;',
    'code_block': 'font-family: "Fira Code", Menlo, "Operator Mono", Consolas, Monaco, monospace; font-size: 0.9em;',
    'footnote-word': 'font-weight: bold; color: #0077ff;',
    'footnote-ref': 'line-height: 0; color: #0077ff; font-weight: bold;',
    'footnotes-sep': 'margin: 2em 0 1em; border-top: 1px solid #0077ff;',
    'footnote-item': 'display: flex; align-items: baseline; margin-bottom: 0.5em;',
    'footnote-num': 'flex-shrink: 0; margin-right: 0.5em; font-size: 80%; color: #0077ff;',
    'footnote-item p': 'margin: 0; font-size: 14px; color: #555;',
}
